### PR TITLE
README code sample typo

### PR DESCRIPTION
**Pull request by atticoos**
`newLen` in the `set` polyfill example was not defined.

I believe this is what it was getting at.. Let me know if i should avoid the ternary and go back to the `if` statement.

### CODE REVIEW

**Comment by keithamus** [comment]
I know it sounds picky, but I would like to split out the ternary. Ideally I'd like it to match spec as closely as it can so we can spot any bugs between the two.

**Comment by ljharb** [comment]
@keithamus you may find it helpful to use https://npmjs.com/es-abstract to represent existing abstract operations, to match the spec even more closely :-D

**Comment by keithamus** [comment]
:+1: happy to do that

**Comment by keithamus** [comment]
Fixed in 6b116d16fbd19a7ce8d20a12791e675fa5b0e345

Thanks for the PR @ajwhite!

**Pull request closed without merging**
